### ISSUE TITLE
More finer level for escape (Java)

### ISSUE THREAD

**Issue by chouclee** [unbescape/unbescape#11]
Hi Daniel,

I like your concept of multiple levels which give developers more flexibility. Considering the following situation (exactly what I have met): 
Huge amount of strings will be processed by Map Reduce program (Java). So I only need to escape \t \n etc single characters and remain other unicode characters still unicode.  Surely I can simply escape them all but this would make it harder to store/process in next steps. What do you think if we split Level 1 in Java into 2 more finer levels? i.e. level 0 only contain basic character set except for non-displayable, control characters. level 1 remains the same. I modified your source code and it was a very small change.

Joe

**Comment by danielfernandez** [comment]
I might be misunderstanding here, but Level 1 seems to do exactly what you need, i.e. escape only non-displayable control characters. I'm not sure about the difference you do between these and "other unicode characters"... every character has a unicode codepoint, are you referring to any specific ranges of control characters that you would want to leave out?

**Comment by chouclee** [comment]
Sorry I made some mistakes. I only want to escape \b, \t, \n, \f, \r, \", \', \\. For other non-display control  characters within range of U+0001 to U+001F and U+007F to U+009F, just ignore them.

**Comment by danielfernandez** [comment]
I understand. However, to be fully honest this setup seems a bit arbitrary to me... I mean, why consider a *level 0* only escaping `\b\t\n\f\r\"\'\.` and not the rest of the current level 1, and not the contrary (escape only U+0001 to U+001F and U+007F to U+009F)? The idea of Level 1 is to have the most basics covered, and that in this case would mean escaping control characters (all of them).

Maybe if I could understand your specific scenario... do you need only specifically these characters escaped and no others because of some standard format you are trying to adopt? 

And also... you mention *large amounts of strings*... but aren't those strings part of `.java` files? and if not... why are you using Java escaping for them?

**Comment by chouclee** [comment]
Good point. They are not part of ```.java``` files. It's just because Java escaping is most suitable for this job. So adding lv0 for Java escaping is a bad idea.

Probably it's better to create some functions to let users choose what characters to escape.

**Comment by danielfernandez** [comment]
IMO, if what you are escaping is not java you should be using an escaping algorithm specific to your scenario. The problem with allowing users to choose which characters to escape is that not only we would have to allow the user to choose the characters to escape, but also how these should be escaped (java-escape, xml-escape, html-escape, sql-escape...? and each escaping method actually allows some characters to be escaped and not others.

In consequence, the complexity of such degree of flexibility would in fact be not too different to actually making users implement their own escaping mechanisms. So I'm afraid I don't see many advantages in this...
