### ISSUE TITLE
XML attribute escaping / unescaping

### ISSUE THREAD

**Issue by nedtwigg** [unbescape/unbescape#12]
Any plans to add support for XML attributes?  In particular, newline encoding support?

**Comment by danielfernandez** [comment]
Unbescape's XML escaping is applicable for both attributes and text. Regarding "newline encoding"... what do you mean?

**Comment by nedtwigg** [comment]
In XML attributes, it's important to escape `\n`, `\t`, and `\r` (that I know of).  [This stackoverflow describes the problem well.](http://stackoverflow.com/questions/2004386/how-to-save-newlines-in-xml-attribute)

For Guava's `XmlEscapers.xmlContentEscaper()` vs `XmlEscapers.xmlAttributeEscaper()`, [this is the difference](https://github.com/google/guava/blob/master/guava/src/com/google/common/xml/XmlEscapers.java#L140-L143).

**Comment by danielfernandez** [comment]
For more detailed reference: `\t`, `\n` and `\r` are actually *valid* characters in XML attributes. But the issue comes from the fact that, according to the [*"Attribute-Value Normalization"*](https://www.w3.org/TR/REC-xml/#AVNormalize) section in the XML spec, when reading attribute values at an XML parser, all these three characters should be normalised to a white-space character, thus provoking a loss of information.

It is necessary therefore to implement a specific set of methods for the escaping of XML attribute values which include *always* (at any level) the escaping of the `\t`, `\n` and `\r` characters.

**Comment by danielfernandez** [comment]
Already in `1.1.5-SNAPSHOT`. Thanks!
