### ISSUE TITLE
Converting escaped readers to unescaped readers (or vice versa)

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [unbescape/unbescape#15]
Hi,

Thanks for an interesting library, and since the library looks powerful and provides what I need, I would like to use it in my project. However, I have a question/request that probably that might look not trivial... Suppose there is a response like this:

```json
"{"foo":"bar: \\\"baz\\\""}"
```

(Not sure if I put backslashes properly) Yes, there are enclosing quotes and the expected response is as follows: ```{"foo":"bar: \"baz\""}```, but due to the specifics of the server I'm not involved to I cannot extract it due to those quotes.

I'm wondering: is it possible to use unbescape in order to transform either ```InputStream``` or ```Reader``` not writing to ```OutputStream``` or ```Writer``` somehow? Why this is necessary: I would like to avoid using intermediate storages like intermediate JSON-parse string (that may be huge) or any other thread-related stuff like ```PipedInputStream```/```PipedOutputStream``` etc. So, something like this:

```java
final Reader unescapedReader = unescapeJson(escapedReader);
...
processNormalizedJsonReader(unescapedReader);
```

Stripping the enclosing quotes would not be hard and I think I could control it myself (like stripping the very first enclosing quote before invoking ```unescapeJson``` to trigger unbescape consider the read content as escaped string; and then detect the very last enclosing and dangling quote myself).

I tried to implement it myself in the simplest way but didn't consider enclosed escapes so my parser fails where there are literals nested at two levels. Here is a question and my failing suggestion (see the **Edit:** section and the ```StringWrapperInputStream``` implementation (input streams are not good anyway)): http://stackoverflow.com/questions/41745307/how-to-parse-json-which-has-escaped-quotes-with-gson/42120149#42120149

Would it be possible with the library?
Thanks!

**Comment by danielfernandez** [comment]
Maybe it's a typo in your text, but assuming this:
```javascript
"{"foo":"bar: \\\"baz\\\""}"
```
…is a JavaScript or JSON text literal, I'm afraid it is ill-formed. The problem is, the quotes around `foo` and `bar:\\\"baz\\\"` are not adequately escaped, so they basically break (stop) the text literal. The correct form of such literal would be:
```javascript
"{\"foo\":\"bar: \\\"baz\\\"\"}"
```
Once you have that, Unbescape should be able to unescape what is inside the quotes as a JSON literal, giving you as a result:
```javascript
{"foo":"bar: \"baz\""}
```
...which is valid JSON/JavaScript object notation, parsable by a JSON parser. Then you could use Unbescape again for unescaping the literal value of the `foo` property but... it should be unnecessary, because the JSON parser would have already done that.

But be aware that, if the value of the `foo` property (`"bar: \"baz\""`) is supposed to be JSON (and not JavaScript), it is also ill-formed, as it should be something like: `"{\"bar\":\"baz\"}"`, and therefore the original literal should look like:
```javascript
"{\"foo\":\"{\\\"bar\\\": \\\"baz\\\"}\"}"
```
Anyway, maybe just a typo in your example, but I mention it just in case your problem is elsewhere.

As for your writer/reader need... let's see if I understand. What you are getting is a (potentially) very large chunk of JSON that might come to you inside a string like the one above (assuming it would be correctly escaped), so you need to JSON-unescape it with Unbescape and pass it to a JSON parser, but without buffering in the middle (and without using `PipedReader`/`PipedWriter`)? So that's why you need Unbescape acting as a nestable `Reader` instead of as a processor… right?

I'm afraid Unbescape is not currently capable of doing that. It wouldn't be impossible, but I don't think it would be very easy either… main issue being that there would still need to be a small amount of buffering meant to contain the last chars of the just-read buffer in case it suspects it could be an unfinished escape sequence (and will not be able to determine until the next `read()`/`close()`).

In the specific case of JSON... that wouldn't be that difficult, as escape sequences are always `\x`, but Unbescape tries to offer the same (or at least equivalent) APIs for all the types of data it escapes/unescapes, and for the HTML case it would get a bit crazier, with much larger escape sequences. Still not impossible, probably… but costly.

**Comment by lyubomyr-shaydariv** [comment]
Hi, and thank you for the quicking response!

> Anyway, maybe just a typo in your example,

Ah, sorry for posting an example with a typo at the end of a working day. You're totally right: there's a typo. I just wanted to put a string value with escaped JSON inside, whilst the JSON also contains escaped quotes inside string literals (like double escaping or whatever good term might fit here well). Supposing the following code is in the Chrome console:

```javascript
> JSON.stringify({"foo":"bar: \"baz\""})
"{"foo":"bar: \"baz\""}"
```

And since the last line is a string literal, this is how a response from that service looks like. (Anyway, there's a workaround for the service with setting Content-Type to application/xml and just extracting Gson-friendly payload between the root XML tags).

>  ... but without buffering in the middle (and without using PipedReader/PipedWriter)? So that's why you need Unbescape acting as a nestable Reader instead of as a processor… right?

You're right for it too: it would be nice not to parse an intermediate string that might be huge in order to parse the real JSON inside of it, and avoiding pipes that also have their cost. At least this is how I see it (and maybe I'm wrong about it). The easiest way of dealing with such responses in Gson is unescaping the reader into an intermediate string first, and then delegate it to the next parser.

>  main issue being that there would still need to be a small amount of buffering meant to contain the last chars of the just-read buffer in case it suspects it could be an unfinished escape sequence (and will not be able to determine until the next read()/close()).

Yes, it would be not an issue to have a small buffer to make peeking for escape sequences (I meant only comparison to probably huge intermediate strings that are total memory waste), and this is what I was failed at in my answer S.O.: my extremely primitive parser only parsed the enclosing quotes, but didn't take into account any nested escapes just because I didn't implement any "deeper" parsing. (Sorry for using probably wrong terms for parsing).

**Comment by danielfernandez** [comment]
Understood, thanks.

Anyway, as I said, this is not currently possible in AttoParser, and right now I'm not planning on performing this type of *semi-important* additions to the feature set in the short term. In order for it to be complete and make sense as a whole it would mean `Reader` wrappers for escaping and unescaping JSON, JavaScript, HTML, XML, etc.

I can leave this open if you want to contribute these ;)…

**Comment by lyubomyr-shaydariv** [comment]
@danielfernandez Unfortunately, I'm afraid it would require too much time and the skills I don't have. Thank you for the exhaustive explanation and interesting comments!
