### ISSUE TITLE
CSS unescape of slash then newline

### ISSUE THREAD

**Issue by rdewell** [unbescape/unbescape#18]
```
 CssEscape.unescapeCss("here\\\nthere")
```

outputs

```
here\
there
```

but based on the reading of the CSS spec it seems like this should be

```
herethere
```

https://www.w3.org/TR/CSS2/syndata.html#escaped-characters

"First, inside a string, a backslash followed by a newline is ignored (i.e., the string is deemed not to contain either the backslash or the newline)"

**Comment by danielfernandez** [comment]
My first impression was that this was actually not an *escape sequence*, but rather a *parsing artifact*. So that it should be handled by parsers automatically and it should never reach the moment of unescaping a CSS string.

However, as you say the CSS 2.1 spec explicitly names this as an escape sequence twice:
   * https://www.w3.org/TR/CSS2/syndata.html#escaped-characters
   * https://www.w3.org/TR/CSS2/syndata.html#strings

To be honest, I believe this is completely wrong. Specifically this phrase:

> First, inside a string, a backslash followed by a newline is ignored (i.e., the string is deemed not to contain either the backslash or the newline). Outside a string, a backslash followed by a newline stands for itself (i.e., a DELIM followed by a newline). 

I don't think that makes sense, as escape sequences *are indeed contained* inside strings. There is no point in saying that a couple of characters should be deemed not to actually exist inside a string and then consider those characters an escape sequence. Building the literal as a lexical unit during parsing is a phase previous to actually unescaping it.

Said in a different way: *escape sequences* are sequences of characters that allow us to express inside literals specific characters that would otherwise *collide* with the established syntax for those literals. That doesn't have anything to do with being able to pretty-print our code by dividing it into several lines because we don't want to go past column number x. That's definitely a parsing artifact.

Anyway, I'll obviously not argue with the specification mantainers on this :), so I'll add this as an unescaping sequence to Unbescape.

**Comment by danielfernandez** [comment]
Already in `1.1.6-SNAPSHOT`
