### ISSUE TITLE
`HtmlEscape.unescapeHtml` throws `IllegalArgumentException` for escapes that are greater than the Unicode range

### ISSUE THREAD

**Issue by b4hand** [unbescape/unbescape#7]
U+110000 is not a valid code point. It exceeds [Plane 16](http://en.wikipedia.org/wiki/Plane_%28Unicode%29). However, HTML in the wild is often dirty, and we've seen poorly formed HTML documents that contain hexadecimal escapes that are *much* larger than the valid range.

This particular case:

```
HtmlEscape.unescapeHtml("&#x110000;");
```

Fails with an `IllegalArgumentException` thrown by [`Character.toChars`](http://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#toChars%28int%29). However, it would be nice if unescaping either ignored these escapes like it does for unknown symbolic escapes such as `HtmlEscape.unescapeHtml("&uumqqq;");` which yields `"&uumqqq;"` as output or replaced them with the Unicode replacement character (U+FFFD).

I'm happy to submit a patch, but I was curious which behavior would be preferred for this edge case.

**Comment by b4hand** [comment]
Decimal escapes have the same issue:

```
// 1114112 == 0x110000
HtmlEscape.unescapeHtml("&#1114112;");
// produces IllegalArgumentException
```

**Comment by b4hand** [comment]
Looking at the unbescape code more closely, it references the [HTML5 specification for handling character references](http://www.w3.org/TR/html5/syntax.html#consume-a-character-reference), which states the following: 

> Otherwise, if the number is in the range 0xD800 to 0xDFFF or is greater than 0x10FFFF, then this is a parse error. Return a U+FFFD REPLACEMENT CHARACTER character token.

Since the code says you're trying to follow this behavior as closely as possible, I'll assume this is a bug and for references greater than 0x10FFFF, it should return U+FFFD.

**Comment by b4hand** [comment]
The next paragraph states the following:

> Otherwise, return a character token for the Unicode character whose code point is that number. Additionally, if the number is in the range 0x0001 to 0x0008, 0x000D to 0x001F, 0x007F to 0x009F, 0xFDD0 to 0xFDEF, or is one of 0x000B, 0xFFFE, 0xFFFF, 0x1FFFE, 0x1FFFF, 0x2FFFE, 0x2FFFF, 0x3FFFE, 0x3FFFF, 0x4FFFE, 0x4FFFF, 0x5FFFE, 0x5FFFF, 0x6FFFE, 0x6FFFF, 0x7FFFE, 0x7FFFF, 0x8FFFE, 0x8FFFF, 0x9FFFE, 0x9FFFF, 0xAFFFE, 0xAFFFF, 0xBFFFE, 0xBFFFF, 0xCFFFE, 0xCFFFF, 0xDFFFE, 0xDFFFF, 0xEFFFE, 0xEFFFF, 0xFFFFE, 0xFFFFF, 0x10FFFE, or 0x10FFFF, then this is a parse error.

It does not specify that the replacement character should be returned in this context, but since the earlier context handles parse errors in that manner, I'm tempted to treat these code points similarly unless you object to that behavior.

**Comment by danielfernandez** [comment]
Thanks for spotting this.

In general, my view is that something like that *"display a `U+FFFD REPLACEMENT CHAR`"* in the HTML5 spec is oriented towards instructing *browsers* how they should display that ill-formed escape sequence, not towards explaining how an unescape operation should work.

My worry here is that doing that (replacing with `U+FFFD`) in tools like this escape/unescape library might go too far as for its true responsibilities. The philosophy IMHO should be more that of *"if something is a valid escape code, then unescape it -- if not, simply leave it"* much in the way those `&#xuumqqq;` are left untouched because they are not recognized as escape sequences.

The problem here is that the unescaping algorithm sees *potentially valid* characters in that sequence (all those `1`s and `0`s are obviously valid hexa) and it doesn't discard the input until it has got all 6 valid hexa digits... but then the value is just above `\u10FFFF`, and that isn't checked before calling `Character.toChars(codepoint)` in `HtmlEscapeUtil:680`. So in my view, unbescape should simply ignore it. There's nothing to *unescape* there from an HTML standpoint, and if a browser wants to show an `\uFFFD`, then it's its job to do so.

And the same goes for all those forbidden ranges. We are not really *parsing HTML* here, we are just replacing escape sequences with their unescaped equivalents.

This said, I'm prepared to discuss this with you if you have a different view. Right now I'm very focused on Thymeleaf --Unbescape's *father* project-- and I haven't had a look at unbescape's code in a while, so the context switch is being a bit complex for me and I might be missing something...

**Comment by b4hand** [comment]
I mostly agree with you. My initial reaction was to simply ignore these illegal escapes as well.

I'll give two counterpoints. First, the cited HTML spec specifically talks about the behavior of validators and non-user agent parsers of HTML, so I do believe its interpretation applies to non-browser behavior.

Secondly, there are some cases that are _already_ being replaced with `U+FFFD`. In particular, the `&#x0000;` and its corresponding decimal escape are already being converted to `U+FFFD`. Thus, when I saw that, I decided to handle the rest of the characters similarly.

For what it is worth, there is a discrepancy between the difference between illegal numeric references and illegal symbolic references. Unknown symbolic references in the HTML spec are simply omitted from the output rather than replaced with `U+FFFD`. (Both are still treated as parse errors.) Thus, if you wanted to fully conform to the spec behavior, you would *drop* unknown symbolic references instead of leaving them as is.

Regardless, if you feel strongly these should be ignored, I'm fine changing the code to do that as well. It's your project after all.

The one concern I have with ignoring the escapes is how would a client know that an illegal escape was observed and/or ignored such that they could take action on it. The current interface doesn't really leave any error reporting channel open. Similarly, I can't see what behavior a client would want to take on ignored escapes, so building in a reporting channel almost seems like wasted effort. The nice thing about the `U+FFFD` replacement is that it is reasonable from a client perspective.

Also, even though the stated purpose of unbescape may not be for HTML parsing, I have to assume the vast majority of clients of your unbescape library that are using the `HtmlEscape` class are probably using it for HTML parsing of some variety.

**Comment by danielfernandez** [comment]
OK, it's taken me quite long to wrap my head around all this... thank you very much for all your comments.

I see what you mean, and you are right that the key aspect here is that unbescape is *already performing a `U+FFFD` transformation*. Not only that, in fact it is performing many of these transformations by means of the conversion table here: https://github.com/unbescape/unbescape/blob/c45e8feb842865c4437885f813784cff4bcef4b0/src/main/java/org/unbescape/html/HtmlEscapeUtil.java#L410-L438 which does what is stated at the HTML5 spec here: http://www.w3.org/TR/html5/syntax.html#tokenizing-character-references

My first impulse was to think that we shouldn't actually be applying such table, because the HTML5 defines those translations as **parse errors** and therefore we are in exactly the same scenario as the one you described for numeric references > `U+10FFFF`: *parse errors* which the spec says should be notified (a thing we cannot do) and afterwards replaced by a different character in output.

But this would be a problem, because that table is used for translating ill-formed escaping codes coming from the old Windows world --which I personally suffered :-(--, and I think it is important that unbescape helps correctly translating those codes into the right characters. Not because of the `&#x0;` -> `U+FFFD` translation, which I don't think is that important, but because of others like `&#x80;` -> `U+20AC` (`€` euro sign), which are a legacy issue huuugely spread here in Europe. The problem is, you cannot do *some* of the translations of that table, it's either all or none.

So **we should go for the `U+FFFD` replacement in the > `U+10FFFF` case** and embrace the HTML5 spec to the maximum extent possible (except the *parse error* signaling, this is). 

In relation to this other paragraph you mention in the HTML5 spec:

> Otherwise, return a character token for the Unicode character whose code point is that number. Additionally, if the number is in the range 0x0001 to 0x0008, 0x000D to 0x001F, 0x007F to 0x009F, 0xFDD0 to 0xFDEF, or is one of 0x000B, 0xFFFE, 0xFFFF, 0x1FFFE, 0x1FFFF, 0x2FFFE, 0x2FFFF, 0x3FFFE, 0x3FFFF, 0x4FFFE, 0x4FFFF, 0x5FFFE, 0x5FFFF, 0x6FFFE, 0x6FFFF, 0x7FFFE, 0x7FFFF, 0x8FFFE, 0x8FFFF, 0x9FFFE, 0x9FFFF, 0xAFFFE, 0xAFFFF, 0xBFFFE, 0xBFFFF, 0xCFFFE, 0xCFFFF, 0xDFFFE, 0xDFFFF, 0xEFFFE, 0xEFFFF, 0xFFFFE, 0xFFFFF, 0x10FFFE, or 0x10FFFF, then this is a parse error. 

As you noted, this paragraph does not state that a `U+FFFD` should be returned in those cases: it says that *the character token for the Unicode character whose code point is that number* should be returned and _**additionally**_, if the codepoint of the returned character was one of those, a parse error should be signaled. But given Unbescape has no way of signaling parse errors, we should leave this responsibility to the users of the library once they have received a character in those ranges (if such error handling applies). So basically I think there's nothing to change here in order to be more *spec-compliant*.

Also, regarding what you say about:
> For what it is worth, there is a discrepancy between the difference between illegal numeric references and illegal symbolic references. Unknown symbolic references in the HTML spec are simply omitted from the output rather than replaced with U+FFFD. (Both are still treated as parse errors.) Thus, if you wanted to fully conform to the spec behavior, you would drop unknown symbolic references instead of leaving them as is.

I'm not sure the spec says that illegal symbolic references should be omitted from output. I think what it says is that a parse error should be signaled for them, and no transformations should be done (which is what Unbescape does). Specifically, it says (in the last *anything else* subsection of 8.2.4.69):
> If no match can be made, then no characters are consumed, and nothing is returned.

Given no characters are consumed, nothing is removed from input, and nothing additional is returned. IMHO this means that output should be the same as input, in this case. That's what Unbescape does.

Note that this is the same instruction the HTML5 spec gives for those cases in which after `&#` comes a series of characters that do not fall in the required numeric range (be it decimal or hexa), like `&#uuqqq;`. In the _"# (U+0023)"_ subsection of 8.2.4.69 it reads:
>If no characters match the range, then don't consume any characters (and unconsume the U+0023 NUMBER SIGN character and, if appropriate, the X character). This is a parse error; nothing is returned.

So, in turn, it seems the only change to be done is reporting codepoints > `U+10FFFF` as `U+FFFD`.

I've also checked all these behaviours on Firefox in order to see how these different cases are displayed. The results match my comments above:

HTML | Displayed by Firefox
-----|-----
`&rarr;` | `→`
`&unknown;` | `&unknown;`
`&#unknown;` | `&#unknown;`
`&#xunknown;` | `&#xunknown;`
`&#x110000;` | `�`
`&#xDFFFF;` | (square with ODFFFF inside)

Note the last one is one of the codepoints included in the list of those for which their corresponding character should be displayed and _additionally_ a parse error should be signaled.

**Comment by b4hand** [comment]
Ok, so for the code points in the big paragraph with no replacement specified, I'll drop mappings in my patch. I'll still test for them, but they should get mapped to literal code points just like "normal" numeric character references.

**Comment by danielfernandez** [comment]
correct. Thanks!

**Comment by b4hand** [comment]
I've updated the PRs and also fixed the additional issue that I found and reported in #9.
